global:
  resolve_timeout: 5m
  smtp_from: '${SMTP_FROM}'
  smtp_smarthost: '${SMTP_SERVER}:${SMTP_PORT}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  group_by: ['alertname', 'instance']
  
  routes:
  - match:
      severity: critical
    receiver: 'pagerduty-critical'
    group_wait: 10s
    continue: true
  
  - match:
      severity: critical
    receiver: 'slack-notifications'
    group_wait: 10s
    continue: true
  
  - match_re:
      severity: ^(warning|critical)$
    receiver: 'email-notifications'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
- name: 'default-receiver'
  email_configs:
  - to: '${SMTP_TO}'
    send_resolved: true
    html: |
      {{ range .Alerts }}
        <h3>{{ .Annotations.summary }}</h3>
        <p>{{ .Annotations.description }}</p>
        <p>
          <strong>Alert:</strong> {{ .Labels.alertname }}<br>
          <strong>State:</strong> {{ .Status }}<br>
          <strong>Severity:</strong> {{ .Labels.severity }}<br>
          <strong>Instance:</strong> {{ .Labels.instance }}<br>
          <strong>Started:</strong> {{ .StartsAt }}
        </p>
      {{ end }}

- name: 'email-notifications'
  email_configs:
  - to: '${SMTP_TO}'
    send_resolved: true
    html: |
      {{ range .Alerts }}
        <h3>{{ .Annotations.summary }}</h3>
        <p>{{ .Annotations.description }}</p>
        <p>
          <strong>Alert:</strong> {{ .Labels.alertname }}<br>
          <strong>State:</strong> {{ .Status }}<br>
          <strong>Severity:</strong> {{ .Labels.severity }}<br>
          <strong>Instance:</strong> {{ .Labels.instance }}<br>
          <strong>Started:</strong> {{ .StartsAt }}
        </p>
      {{ end }}

- name: 'slack-notifications'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts'
    send_resolved: true
    title: '{{ .CommonAnnotations.summary }}'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Labels.alertname }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Instance:* {{ .Labels.instance }}
      {{ end }}

- name: 'pagerduty-critical'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_SERVICE_KEY}'
    description: '{{ .CommonAnnotations.summary }}'
    client: 'AlertManager'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    details:
      description: '{{ .CommonAnnotations.description }}'
      severity: '{{ .CommonLabels.severity }}'
      instance: '{{ .CommonLabels.instance }}'

# Optional Slack configuration
# - name: 'slack-notifications'
#   slack_configs:
#   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
#     channel: '#alerts'
#     send_resolved: true 