groups:
  - name: server_alerts
    rules:
      - alert: HighCPULoad
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU load (instance {{ $labels.instance }})"
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage (instance {{ $labels.instance }})"
          description: "Memory usage is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: api_alerts
    rules:
      - alert: APIHighResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "API High Response Time"
          description: "95th percentile of HTTP response time is above 1 second\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          
      - alert: APIHighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "API High Error Rate"
          description: "Error rate is above 5%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: APIDown
        expr: up{job="fastapi"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API is down"
          description: "FastAPI instance is down for more than 1 minute"

      - alert: LowDiskSpace
        expr: 100 - ((node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk usage is above 90% ({{ $value | humanizePercentage }})"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[1m]) / rate(http_requests_total[1m]) > 0.05
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Error Rate"
          description: "Error rate is above 5%\n  VALUE = {{ $value | humanizePercentage }}\n  LABELS = {{ $labels }}"

      - alert: CriticalErrorRate
        expr: rate(http_requests_total{status=~"5.."}[1m]) / rate(http_requests_total[1m]) > 0.15
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Critical Error Rate"
          description: "Error rate is above 15%\n  VALUE = {{ $value | humanizePercentage }}\n  LABELS = {{ $labels }}"

  - name: database_alerts
    rules:
      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, sum(rate(database_query_duration_seconds_bucket[5m])) by (le, query_type)) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Slow Database Queries"
          description: "95th percentile of database query time is above 500ms for query type {{ $labels.query_type }}\n  VALUE = {{ $value }}s\n  LABELS = {{ $labels }}"